### PR TITLE
fix: Escape html code to prevent XSS

### LINKED ISSUE #13: Escape string values returned by the API to avoid XSS
Do you have any concerns about the fact that we are not escaping the string values and thus possibly introducing [an XSS vulnerability](https://owasp.org/www-community/attacks/xss/)?

A possible fix - use a library like https://www.npmjs.com/package/escape-goat

```js
import { htmlEscape } from 'https://cdn.jsdelivr.net/npm/escape-goat@4.0.0/+esm'

return htmlEscape`
    <div class="network-item">
      <span class="network-name">${network.name}</span>
      <span class="success-rate">${network.successRate.toFixed(2)}%</span>
    </div>
  `
```

_Originally posted by @bajtos in https://github.com/CheckerNetwork/leaderboard/pull/11#discussion_r1991698830_

### PR DESCRIPTION
**Pull request by pyropy**
Fixes potential XSS vulnerability by escaping dynamic HTML content. Generated HTML is escaped using `escape-goat` library which is loaded using JS importmaps. 

Closes #13

### CODE REVIEW

**Review by bajtos — APPROVED** [review]
🙏🏻

File: src/js/script.js [hunk 1]
```diff
@@ -76,7 +77,7 @@ export async function fetchNetworkData (networkName) {
  * @returns {string} HTML string for the network item
  */
 export function createNetworkItemHTML (network) {
-  return `
+  return htmlEscape`
```
Comment (juliangruber) [inline src/js/script.js:80]: This is why you use React - by definition it's impossible to insert HTML from server responses
